// Video hotspot configuration — hand-edited, unlike hotspot-config.js.
//
// hotspot-config.js is regenerated by MetaRoom3D every time a floor's GLB is
// re-exported, so anything added there gets wiped. This file is loaded
// separately by hotspots.js and is never touched by the exporter.
//
// Coordinates use exactly the same phi/theta/radius space as hotspotData in
// hotspot-config.js, so the quickest way to place a panel is to copy the
// phi/theta of a nav hotspot that already sits near where you want it, then
// nudge from there.
//
//   theta  azimuth in radians, -PI..PI
//   phi    polar angle in radians. PI/2 (1.5708) is the horizon;
//          LARGER is below the horizon, smaller is above.
//          Your nav hotspots sit around 1.75-1.95, i.e. on the floor.
//   radius keep below the 500-unit photo sphere so the panel sits in front
//          of the photo rather than z-fighting with it. 480 matches your
//          existing hotspots.

export const videoHotspotData = [
  {
    // The blank wall to the right of the front door in Foyer.jpg — the area
    // circled in the reference screenshot.
    panoramaImage: 'panos/Foyer.jpg',
    videoId: 'hO5iKRZdp3c',   // https://youtu.be/hO5iKRZdp3c

    radius: 370,
    theta: 1.3,              // start here, then nudge to line up with the wall
    phi: 1.72,                // just above the horizon, roughly eye level

    width: 520,               // world units, ~13 degrees across at radius 470
    aspect: 16 / 9,
    rollDeg: 0,               // tilt, for screens that aren't level in the shot
	tiltDeg: 0,
	yawDeg: 0, 
	

    autoplay: true,           // forced muted — browsers block unmuted autoplay
    loop: true,
  },
];
