// Generated Hotspot Configuration
// Auto-generated by MetaRoom3D — merges every floor exported into this folder.
// Do not hand-edit; re-exporting a floor's GLB regenerates this file from
// .hotspot-cache.json (also in this folder), which is what actually gets merged.

export const hotspotData = [
  {
    theta: 0.1439,
    phi: 1.6974,
    radius: 480,
    color: 0xff6600,
    name: '08ded219-6641-42b0-8ea0-8dbb0c720aeb',
    panoramaImage: 'panos/08ded219-6641-42b0-8ea0-8dbb0c720aeb.jpg',
    fromRoom: '08ded219-539a-44d4-8a5b-58f09a692004'
  },
  {
    theta: -1.3494,
    phi: 1.7705,
    radius: 480,
    color: 0xff6600,
    name: '08ded219-539a-44d4-8a5b-58f09a692004',
    panoramaImage: 'panos/08ded219-539a-44d4-8a5b-58f09a692004.jpg',
    fromRoom: '08ded219-6641-42b0-8ea0-8dbb0c720aeb'
  },
  {
    theta: 0.0046,
    phi: 2.1939,
    radius: 480,
    color: 0xff6600,
    name: '08ded219-539a-44d4-8a5b-58f09a692004',
    panoramaImage: 'panos/08ded219-539a-44d4-8a5b-58f09a692004.jpg',
    fromRoom: '08ded219-9be0-4423-804c-2bbf92c594d2'
  },
  {
    theta: -1.4989,
    phi: 1.7519,
    radius: 480,
    color: 0xff6600,
    name: '08ded219-539a-44d4-8a5b-58f09a692004',
    panoramaImage: 'panos/08ded219-539a-44d4-8a5b-58f09a692004.jpg',
    fromRoom: '08ded219-a204-4c35-8316-393076e8cd5b'
  }
];

export const roomConnections = {
  '08ded219-539a-44d4-8a5b-58f09a692004': ['08ded219-6641-42b0-8ea0-8dbb0c720aeb'],
  '08ded219-6641-42b0-8ea0-8dbb0c720aeb': ['08ded219-539a-44d4-8a5b-58f09a692004'],
  '08ded219-9be0-4423-804c-2bbf92c594d2': ['08ded219-539a-44d4-8a5b-58f09a692004'],
  '08ded219-a204-4c35-8316-393076e8cd5b': ['08ded219-539a-44d4-8a5b-58f09a692004']
};

export const availablePanoramas = [
  'panos/08ded219-539a-44d4-8a5b-58f09a692004.jpg',
  'panos/08ded219-6641-42b0-8ea0-8dbb0c720aeb.jpg',
  'panos/08ded219-9be0-4423-804c-2bbf92c594d2.jpg',
  'panos/08ded219-a204-4c35-8316-393076e8cd5b.jpg'
];

export const modelToPanoramaMapping = [
  {
    nodeNamePatterns: ['08ded219-539a-44d4-8a5b-58f09a692004'],
    fallbackIndex: 0,
    panoramaImage: 'panos/08ded219-539a-44d4-8a5b-58f09a692004.jpg',
    displayName: '08ded219-539a-44d4-8a5b-58f09a692004'
  },
  {
    nodeNamePatterns: ['08ded219-6641-42b0-8ea0-8dbb0c720aeb'],
    fallbackIndex: 1,
    panoramaImage: 'panos/08ded219-6641-42b0-8ea0-8dbb0c720aeb.jpg',
    displayName: '08ded219-6641-42b0-8ea0-8dbb0c720aeb'
  },
  {
    nodeNamePatterns: ['08ded219-9be0-4423-804c-2bbf92c594d2'],
    fallbackIndex: 2,
    panoramaImage: 'panos/08ded219-9be0-4423-804c-2bbf92c594d2.jpg',
    displayName: '08ded219-9be0-4423-804c-2bbf92c594d2'
  },
  {
    nodeNamePatterns: ['08ded219-a204-4c35-8316-393076e8cd5b'],
    fallbackIndex: 3,
    panoramaImage: 'panos/08ded219-a204-4c35-8316-393076e8cd5b.jpg',
    displayName: '08ded219-a204-4c35-8316-393076e8cd5b'
  }
];
